name: Sync JSON to Supabase

on:
  push:
    branches:
          - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Link Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_URL }}
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Run Supabase migrations
        run: supabase db push
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

              --data-binary @"$file"
          done
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
