name: Sync JSON to Supabase

on:
  push:
    branches:
      - main
    paths:
      - '*.json'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Link Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Run Supabase Migrations
        run: supabase db push
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Upload JSON data to Supabase
        env:
          SUPABASE_URL: https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          for file in *.json; do
            table="${file%.json}"
            echo "Uploading $file to table $table"
            curl -X POST "$SUPABASE_URL/rest/v1/$table" \
              -H "apikey: $SUPABASE_KEY" \
              -H "Authorization: Bearer $SUPABASE_KEY" \
              -H "Content-Type: application/json" \
              --data-binary @"$file"
          done
